# Generated by Django 6.0.1 on 2026-01-30 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_items', '0002_alter_orderitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
